name: 'PR Automation'
description: 'Automatically update, merge, mark stale, mark un-stale and close pull requests.'
branding:
  icon: check
  color: green
inputs:
  token:
    description: 'Token to authenticate with when connecting to Github'
    required: true
  autoCloseLabel:
    description: 'Label of PRs to be automatically closed (or * for all PRs)'
    default: 'auto-close'
    required: false
  autoMergeLabel:
    description: 'Label of PRs to be automatically merged (or * for all PRs)'
    default: 'auto-merge'
    required: false
  warnClosingAfter:
    description: 'Warn user their PR will be closed after it has been open for x duration (can be specified as 1s,2m,3h etc)'
    default: '3d'
    required: false
  autoCloseAfterWarn:
    description: 'Auto close PRs x duration after author has been warned (can be specified as 1s,2m,3h etc)'
    default: '1d'
    required: false
  closingSoonComment:
    description: 'Comment to post on PRs that are closing soon'
    default: 'This pull request is inactive and will be closed at @closeTime'
    required: false
  closingSoonLabel:
    description: 'Label to apply to PRs that are closing soon'
    default: 'closing-soon'
    required: false
  deleteOnMerge:
    description: 'Delete branch once PR has been merged'
    default: 'false'
    required: false
  deleteOnClose:
    description: 'Delete branch if PR is closed'
    default: 'false'
    required: false
  branchBlackList:
    description: 'PRs where these branches are the base or head will be ignored.'
    default: 'master'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
