name: 'PR Automation'
description: 'Automatically update pull requests if required, merge pull requests once any checks/approvals have passed. Comment on and label pull requests that are becoming stale and then close them. Once a PR has been merged/closed it can also delete the branch.'
branding:
  icon: check
  color: green
inputs:
  token:
    description: 'Token to authenticate with when connecting to Github'
    required: true
  autoCloseLabel:
    description: 'Label of PRs to be automatically closed'
    required: false
  autoMergeLabel:
    description: 'Label of PRs to be automatically merged'
    required: false
  warnClosingAfterSecs:
    description: 'Warn user their PR will be closed after it has been open for x secs'
    required: false
  autoCloseAfterWarnSecs:
    description: 'Auto close PRs secs after author has been warned'
    required: false
  closingSoonComment:
    description: 'Comment to post on PRs that are closing soon'
    default: 'This pull request is inactive and will be closed at @closeTime'
    required: false
  closingSoonLabel:
    description: 'Label to apply to PRs that are closing soon'
    default: 'closing-soon'
    required: false
  deleteOnMerge:
    description: 'Delete branch once PR has been merged'
    default: 'false'
    required: false
  deleteOnClose:
    description: 'Delete branch if PR is closed'
    default: 'false'
    required: false
  branchBlackList:
    description: 'PRs where these branches are the base or head will be ignored.'
    default: 'master'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
